### ISSUE TITLE
configure `theme_style` as `dark` 

### ISSUE THREAD

**Issue by evawyf** [levblanc/hexo-theme-aero-dual#1]
I'm wondering which file may configure `theme_style` as `dark`? 
Thanks!

**Comment by asd7227600** [comment]
@elvawyf 

Add `theme_style: dark` in `./Hexo/_config.yml`

**Comment by levblanc** [comment]
@elvawyf @asd7227600 

In your blog's main `_config.yml`.  

Just put it under your `theme` config so that you have them together in one place. That would be easier to manage if you want to modify them in the future.

Thought the question was answered. Checked this morning and found the bug in my README.md. :P 

Sorry for the late reply.
